/**
 * Downloadable resources served from R2 through /api/resources/<key>.
 * Only keys listed here can be requested. Files are generated by
 * `npm run resources` into ./resources and uploaded with wrangler (README).
 */
export interface ResourceItem {
  key: string;
  title: string;
  description: string;
  filename: string;
  contentType: string;
}

export const RESOURCES: ResourceItem[] = [
  {
    key: 'cloudflare-migration-checklist.md',
    title: 'Cloudflare migration checklist',
    description: 'The condensed runbook: inventory, DNS, TLS, redirects, protection, cutover, rollback and the post-launch review. Markdown, so it goes straight into your own docs.',
    filename: 'xolqy-cloudflare-migration-checklist.md',
    contentType: 'text/markdown; charset=utf-8',
  },
];

export function findResource(key: string): ResourceItem | undefined {
  return RESOURCES.find((r) => r.key === key);
}
