/** Site-wide constants. Business details that are not yet known are left out
 *  on purpose rather than invented; see README > "Missing business details". */
export const SITE = {
  name: 'Xolqy',
  wordmark: 'xolqy',
  domain: 'xolqy.com',
  url: 'https://xolqy.com',
  tagline: 'Built for the edge.',
  description:
    'Xolqy is an independent agency that designs, builds, migrates, secures and manages businesses on Cloudflare: fast websites, scalable applications, secure infrastructure and useful AI.',
  locale: 'en',
  // Social preview image generated by `npm run og` into public/og/.
  defaultOgImage: '/og/default.png',
  // Not affiliated with Cloudflare, Inc. Stated on every page footer.
  independenceNote:
    'Xolqy is an independent agency. It is not affiliated with, endorsed by or certified by Cloudflare, Inc. Cloudflare is a trademark of Cloudflare, Inc.',
} as const;

export const NAV = [
  { label: 'Services', href: '/services/' },
  { label: 'Work', href: '/work/' },
  { label: 'Our Stack', href: '/stack/' },
  { label: 'Labs', href: '/labs/' },
  { label: 'Insights', href: '/insights/' },
  { label: 'Wiki', href: '/wiki/' },
  { label: 'About', href: '/about/' },
] as const;

export const CTA = {
  primary: { label: 'Start your project', href: '/contact/' },
  secondary: { label: 'Explore our Cloudflare stack', href: '/stack/' },
} as const;

export const SERVICE_ORDER = [
  'websites-and-applications',
  'cloudflare-migration',
  'performance-and-delivery',
  'security-and-zero-trust',
  'ai-and-automation',
  'managed-cloudflare',
] as const;

export type ServiceSlug = (typeof SERVICE_ORDER)[number];

/** Options offered in the enquiry form. Values are stored in D1 as-is. */
export const SERVICE_INTERESTS: { value: string; label: string }[] = [
  { value: 'websites-and-applications', label: 'Websites & Applications' },
  { value: 'cloudflare-migration', label: 'Cloudflare Migration' },
  { value: 'performance-and-delivery', label: 'Performance & Delivery' },
  { value: 'security-and-zero-trust', label: 'Security & Zero Trust' },
  { value: 'ai-and-automation', label: 'AI & Automation' },
  { value: 'managed-cloudflare', label: 'Managed Cloudflare' },
  { value: 'audit', label: 'Cloudflare Audit' },
  { value: 'not-sure', label: 'Not sure yet' },
];

export const BUDGET_RANGES: { value: string; label: string }[] = [
  { value: '', label: 'Prefer not to say' },
  { value: 'under-5k', label: 'Under €5k' },
  { value: '5k-15k', label: '€5k to €15k' },
  { value: '15k-40k', label: '€15k to €40k' },
  { value: '40k-plus', label: '€40k and above' },
  { value: 'retainer', label: 'Monthly retainer' },
];
